# Generated by Django 4.2.9 on 2026-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_store_produ_categor_591340_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peso_max_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Peso máximo de mascota recomendado (kg)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_min_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Peso mínimo de mascota recomendado (kg)', max_digits=5, null=True),
        ),
    ]
