# Generated by Django 4.2.9 on 2026-05-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto de tu mascota (opcional)', null=True, upload_to='mascotas/'),
        ),
    ]
