# Generated by Django 4.2.9 on 2026-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pais',
            field=models.CharField(blank=True, max_length=10, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Saldo virtual'),
        ),
    ]
